data:
    train_path: ../crop_part1/train/
    val_path: ../crop_part1/val/
    out_model_path: ./efnetb0.pkl
training:
    loss: mse
    batch_size: 32
    epochs: 20
    learning_rate: 1e-3
    max_data: 0
    optimizer: adam
logging:
    mlflow_url: "http://localhost:8886"
